apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodemon-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodemon-frontend
  template:
    metadata:
      labels:
        app: nodemon-frontend
    spec:
      containers:
      - name: nodemon-frontend
        image: nodemon-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf # Mount the file, not the directory
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config